sudo: required

language: go
go:
  - 1.9.x

services:
  - docker
  
before_install:
  - curl https://glide.sh/get | sh

jobs:
  include:
    - stage: check-code
      script: make vet & make lint
      env: _=Running go vet, go lint
    - stage: test-unit
      script: make test
      env: _=Running full unit tests
    - stage: test-int
      script: make testInt-store-mongodb
      env: _=Integration tests for store-mongodb module
    - stage: test-int
      script: make testInt-api
      env: _=Integration tests for api module
    - stage: publish
      if: branch = master
      script: make publish-store-mongodb
      env: _=Publishing store-mongodb module
    - stage: publish
      if: branch = master
      script: make publish-api
      env: _=Publishing api module
