sudo: required

language: go
go:
  - 1.9.x

services:
  - docker
  
before_install:
  - curl https://glide.sh/get | sh

jobs:
  include:
    - stage: check-code
      script: make vet
      env: _=Running go vet
    - stage: check-code
      script: make lint
      env: _=Running gofmt
    - stage: test-unit
      script: make test
      env: _=Running full unit tests
    - stage: test-int
      script: make testInt-store-mongodb
      env: _=Integration tests for store-mongodb module
    - stage: test-int
      script: make testInt-api
      env: _=Integration tests for api module
    - stage: release
      script: make release-store-mongodb
      env: _=Releasing store-mongodb module
    - stage: release
      script: make release-api
      env: _=Releasing api module