// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job/common.proto

/*
Package job is a generated protocol buffer package.

It is generated from these files:
	job/common.proto
	job/request.proto
	job/response.proto
	job/service.proto

It has these top-level messages:
	CreateJobRequest
	CreateJobResponse
*/
package job

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JobType int32

const (
	JobType_PUBLIC  JobType = 0
	JobType_PRIVATE JobType = 1
)

var JobType_name = map[int32]string{
	0: "PUBLIC",
	1: "PRIVATE",
}
var JobType_value = map[string]int32{
	"PUBLIC":  0,
	"PRIVATE": 1,
}

func (x JobType) String() string {
	return proto.EnumName(JobType_name, int32(x))
}
func (JobType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type JobStatus int32

const (
	JobStatus_CREATED   JobStatus = 0
	JobStatus_SUSPENDED JobStatus = 1
	JobStatus_DELETED   JobStatus = 3
)

var JobStatus_name = map[int32]string{
	0: "CREATED",
	1: "SUSPENDED",
	3: "DELETED",
}
var JobStatus_value = map[string]int32{
	"CREATED":   0,
	"SUSPENDED": 1,
	"DELETED":   3,
}

func (x JobStatus) String() string {
	return proto.EnumName(JobStatus_name, int32(x))
}
func (JobStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterEnum("job.JobType", JobType_name, JobType_value)
	proto.RegisterEnum("job.JobStatus", JobStatus_name, JobStatus_value)
}

func init() { proto.RegisterFile("job/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0xca, 0x4f, 0xd2,
	0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0xca,
	0x4f, 0xd2, 0x52, 0xe2, 0x62, 0xf7, 0xca, 0x4f, 0x0a, 0xa9, 0x2c, 0x48, 0x15, 0xe2, 0xe2, 0x62,
	0x0b, 0x08, 0x75, 0xf2, 0xf1, 0x74, 0x16, 0x60, 0x10, 0xe2, 0xe6, 0x62, 0x0f, 0x08, 0xf2, 0x0c,
	0x73, 0x0c, 0x71, 0x15, 0x60, 0xd4, 0x32, 0xe1, 0xe2, 0xf4, 0xca, 0x4f, 0x0a, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0x06, 0xc9, 0x38, 0x07, 0xb9, 0x3a, 0x86, 0xb8, 0xba, 0x08, 0x30, 0x08, 0xf1, 0x72,
	0x71, 0x06, 0x87, 0x06, 0x07, 0xb8, 0xfa, 0xb9, 0xb8, 0xba, 0x08, 0x30, 0x82, 0xe4, 0x5c, 0x5c,
	0x7d, 0x5c, 0x41, 0x72, 0xcc, 0x49, 0x6c, 0x60, 0x5b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x49, 0x91, 0x1d, 0x07, 0x79, 0x00, 0x00, 0x00,
}
