// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scheduler/common.proto

/*
Package scheduler is a generated protocol buffer package.

It is generated from these files:
	scheduler/common.proto
	scheduler/request.proto
	scheduler/response.proto
	scheduler/service.proto

It has these top-level messages:
	SchedulerProperty
	SchedulerMeta
	Scheduler
	CreateSchedulerRequest
	UpdateSchedulerRequest
	DeleteSchedulerRequest
	GetSchedulerRequest
	CreateSchedulerResponse
*/
package scheduler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SchedulerType int32

const (
	SchedulerType_PUBLIC  SchedulerType = 0
	SchedulerType_PRIVATE SchedulerType = 1
)

var SchedulerType_name = map[int32]string{
	0: "PUBLIC",
	1: "PRIVATE",
}
var SchedulerType_value = map[string]int32{
	"PUBLIC":  0,
	"PRIVATE": 1,
}

func (x SchedulerType) String() string {
	return proto.EnumName(SchedulerType_name, int32(x))
}
func (SchedulerType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SchedulerStatus int32

const (
	SchedulerStatus_CREATED   SchedulerStatus = 0
	SchedulerStatus_SUSPENDED SchedulerStatus = 1
	SchedulerStatus_DELETED   SchedulerStatus = 3
)

var SchedulerStatus_name = map[int32]string{
	0: "CREATED",
	1: "SUSPENDED",
	3: "DELETED",
}
var SchedulerStatus_value = map[string]int32{
	"CREATED":   0,
	"SUSPENDED": 1,
	"DELETED":   3,
}

func (x SchedulerStatus) String() string {
	return proto.EnumName(SchedulerStatus_name, int32(x))
}
func (SchedulerStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SchedulerProperty struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*SchedulerProperty_Value
	//	*SchedulerProperty_Child
	Content isSchedulerProperty_Content `protobuf_oneof:"content"`
}

func (m *SchedulerProperty) Reset()                    { *m = SchedulerProperty{} }
func (m *SchedulerProperty) String() string            { return proto.CompactTextString(m) }
func (*SchedulerProperty) ProtoMessage()               {}
func (*SchedulerProperty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isSchedulerProperty_Content interface {
	isSchedulerProperty_Content()
}

type SchedulerProperty_Value struct {
	Value string `protobuf:"bytes,2,opt,name=value,oneof"`
}
type SchedulerProperty_Child struct {
	Child *SchedulerProperty `protobuf:"bytes,3,opt,name=child,oneof"`
}

func (*SchedulerProperty_Value) isSchedulerProperty_Content() {}
func (*SchedulerProperty_Child) isSchedulerProperty_Content() {}

func (m *SchedulerProperty) GetContent() isSchedulerProperty_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *SchedulerProperty) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SchedulerProperty) GetValue() string {
	if x, ok := m.GetContent().(*SchedulerProperty_Value); ok {
		return x.Value
	}
	return ""
}

func (m *SchedulerProperty) GetChild() *SchedulerProperty {
	if x, ok := m.GetContent().(*SchedulerProperty_Child); ok {
		return x.Child
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SchedulerProperty) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SchedulerProperty_OneofMarshaler, _SchedulerProperty_OneofUnmarshaler, _SchedulerProperty_OneofSizer, []interface{}{
		(*SchedulerProperty_Value)(nil),
		(*SchedulerProperty_Child)(nil),
	}
}

func _SchedulerProperty_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SchedulerProperty)
	// content
	switch x := m.Content.(type) {
	case *SchedulerProperty_Value:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Value)
	case *SchedulerProperty_Child:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Child); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SchedulerProperty.Content has unexpected type %T", x)
	}
	return nil
}

func _SchedulerProperty_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SchedulerProperty)
	switch tag {
	case 2: // content.value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Content = &SchedulerProperty_Value{x}
		return true, err
	case 3: // content.child
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SchedulerProperty)
		err := b.DecodeMessage(msg)
		m.Content = &SchedulerProperty_Child{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SchedulerProperty_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SchedulerProperty)
	// content
	switch x := m.Content.(type) {
	case *SchedulerProperty_Value:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Value)))
		n += len(x.Value)
	case *SchedulerProperty_Child:
		s := proto.Size(x.Child)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SchedulerMeta struct {
	CreatedBy          string                     `protobuf:"bytes,1,opt,name=createdBy" json:"createdBy,omitempty"`
	CreatedOn          *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=createdOn" json:"createdOn,omitempty"`
	LastModificationBy string                     `protobuf:"bytes,3,opt,name=lastModificationBy" json:"lastModificationBy,omitempty"`
	LastModificationOn *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=lastModificationOn" json:"lastModificationOn,omitempty"`
}

func (m *SchedulerMeta) Reset()                    { *m = SchedulerMeta{} }
func (m *SchedulerMeta) String() string            { return proto.CompactTextString(m) }
func (*SchedulerMeta) ProtoMessage()               {}
func (*SchedulerMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SchedulerMeta) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *SchedulerMeta) GetCreatedOn() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *SchedulerMeta) GetLastModificationBy() string {
	if m != nil {
		return m.LastModificationBy
	}
	return ""
}

func (m *SchedulerMeta) GetLastModificationOn() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastModificationOn
	}
	return nil
}

type Scheduler struct {
	Id          string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Description string                     `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Expression  string                     `protobuf:"bytes,3,opt,name=expression" json:"expression,omitempty"`
	Labels      []string                   `protobuf:"bytes,4,rep,name=labels" json:"labels,omitempty"`
	Type        SchedulerType              `protobuf:"varint,5,opt,name=type,enum=scheduler.SchedulerType" json:"type,omitempty"`
	Status      SchedulerStatus            `protobuf:"varint,6,opt,name=status,enum=scheduler.SchedulerStatus" json:"status,omitempty"`
	StartDate   *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=startDate" json:"startDate,omitempty"`
	EndDate     *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=endDate" json:"endDate,omitempty"`
	Properties  []*SchedulerProperty       `protobuf:"bytes,9,rep,name=properties" json:"properties,omitempty"`
	Meta        *SchedulerMeta             `protobuf:"bytes,10,opt,name=meta" json:"meta,omitempty"`
}

func (m *Scheduler) Reset()                    { *m = Scheduler{} }
func (m *Scheduler) String() string            { return proto.CompactTextString(m) }
func (*Scheduler) ProtoMessage()               {}
func (*Scheduler) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Scheduler) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Scheduler) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Scheduler) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

func (m *Scheduler) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Scheduler) GetType() SchedulerType {
	if m != nil {
		return m.Type
	}
	return SchedulerType_PUBLIC
}

func (m *Scheduler) GetStatus() SchedulerStatus {
	if m != nil {
		return m.Status
	}
	return SchedulerStatus_CREATED
}

func (m *Scheduler) GetStartDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *Scheduler) GetEndDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *Scheduler) GetProperties() []*SchedulerProperty {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Scheduler) GetMeta() *SchedulerMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*SchedulerProperty)(nil), "scheduler.SchedulerProperty")
	proto.RegisterType((*SchedulerMeta)(nil), "scheduler.SchedulerMeta")
	proto.RegisterType((*Scheduler)(nil), "scheduler.Scheduler")
	proto.RegisterEnum("scheduler.SchedulerType", SchedulerType_name, SchedulerType_value)
	proto.RegisterEnum("scheduler.SchedulerStatus", SchedulerStatus_name, SchedulerStatus_value)
}

func init() { proto.RegisterFile("scheduler/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x6e, 0xda, 0x40,
	0x10, 0xc6, 0x31, 0xe6, 0x4f, 0x3d, 0x28, 0x29, 0x9d, 0x03, 0x5a, 0xa1, 0xa8, 0xb5, 0x38, 0xa1,
	0xa8, 0x32, 0x12, 0xcd, 0xa1, 0xaa, 0x7a, 0x09, 0xc1, 0x52, 0x53, 0x25, 0x0d, 0x5a, 0x48, 0xef,
	0x8b, 0x3d, 0x49, 0xac, 0x1a, 0xaf, 0xe5, 0x5d, 0xaa, 0x72, 0xe9, 0x4b, 0xf5, 0x91, 0xfa, 0x22,
	0xd5, 0xae, 0xc1, 0x41, 0x0d, 0x12, 0x37, 0xef, 0x7c, 0xbf, 0xf1, 0xcc, 0x37, 0x33, 0xd0, 0x53,
	0xd1, 0x13, 0xc5, 0xeb, 0x94, 0x8a, 0x51, 0x24, 0x57, 0x2b, 0x99, 0x05, 0x79, 0x21, 0xb5, 0x44,
	0xaf, 0x8a, 0xf7, 0xdf, 0x3d, 0x4a, 0xf9, 0x98, 0xd2, 0xc8, 0x0a, 0xcb, 0xf5, 0xc3, 0x48, 0x27,
	0x2b, 0x52, 0x5a, 0xac, 0xf2, 0x92, 0x1d, 0xfc, 0x86, 0x37, 0xf3, 0x1d, 0x3d, 0x2b, 0x64, 0x4e,
	0x85, 0xde, 0x60, 0x17, 0xdc, 0x1f, 0xb4, 0x61, 0x8e, 0xef, 0x0c, 0x3d, 0x6e, 0x3e, 0xb1, 0x07,
	0xcd, 0x9f, 0x22, 0x5d, 0x13, 0xab, 0x9b, 0xd8, 0x97, 0x1a, 0x2f, 0x9f, 0x78, 0x01, 0xcd, 0xe8,
	0x29, 0x49, 0x63, 0xe6, 0xfa, 0xce, 0xb0, 0x33, 0x3e, 0x0b, 0xaa, 0xd2, 0xc1, 0x8b, 0xdf, 0x9a,
	0x2c, 0x0b, 0x4f, 0x3c, 0x68, 0x47, 0x32, 0xd3, 0x94, 0xe9, 0xc1, 0x5f, 0x07, 0x4e, 0x2a, 0xf2,
	0x96, 0xb4, 0xc0, 0x33, 0xf0, 0xa2, 0x82, 0x84, 0xa6, 0x78, 0xb2, 0x6b, 0xe1, 0x39, 0x80, 0x1f,
	0x2b, 0xf5, 0x2e, 0xb3, 0xcd, 0x74, 0xc6, 0xfd, 0xa0, 0x34, 0x19, 0xec, 0x4c, 0x06, 0x8b, 0x9d,
	0x49, 0xfe, 0x0c, 0x63, 0x00, 0x98, 0x0a, 0xa5, 0x6f, 0x65, 0x9c, 0x3c, 0x24, 0x91, 0xd0, 0x89,
	0xcc, 0x26, 0x1b, 0xdb, 0xb7, 0xc7, 0x0f, 0x28, 0xf8, 0xf5, 0x25, 0x7f, 0x97, 0xb1, 0xc6, 0xd1,
	0x92, 0x07, 0xb2, 0x06, 0x7f, 0x5c, 0xf0, 0x2a, 0x97, 0x78, 0x0a, 0xf5, 0x24, 0xde, 0x5a, 0xab,
	0x27, 0x31, 0xfa, 0xd0, 0x89, 0x49, 0x45, 0x45, 0x92, 0x1b, 0xbc, 0x1c, 0x31, 0xdf, 0x0f, 0xe1,
	0x5b, 0x00, 0xfa, 0x95, 0x17, 0xa4, 0x94, 0x01, 0xca, 0x9e, 0xf7, 0x22, 0xd8, 0x83, 0x56, 0x2a,
	0x96, 0x94, 0x2a, 0xd6, 0xf0, 0xdd, 0xa1, 0xc7, 0xb7, 0x2f, 0x7c, 0x0f, 0x0d, 0xbd, 0xc9, 0x89,
	0x35, 0x7d, 0x67, 0x78, 0x3a, 0x66, 0x87, 0xb6, 0xb3, 0xd8, 0xe4, 0xc4, 0x2d, 0x85, 0x63, 0x68,
	0x29, 0x2d, 0xf4, 0x5a, 0xb1, 0x96, 0xe5, 0xfb, 0x87, 0xf8, 0xb9, 0x25, 0xf8, 0x96, 0x34, 0xfb,
	0x50, 0x5a, 0x14, 0x7a, 0x2a, 0x34, 0xb1, 0xf6, 0xf1, 0x7d, 0x54, 0x30, 0x5e, 0x40, 0x9b, 0xb2,
	0xd8, 0xe6, 0xbd, 0x3a, 0x9a, 0xb7, 0x43, 0xf1, 0x33, 0x40, 0x5e, 0xde, 0x53, 0x42, 0x8a, 0x79,
	0xbe, 0x7b, 0xec, 0xea, 0xf8, 0x1e, 0x6f, 0xe6, 0xb1, 0x22, 0x2d, 0x18, 0xd8, 0x82, 0x07, 0xe7,
	0x61, 0x6e, 0x90, 0x5b, 0xea, 0x7c, 0xb8, 0x77, 0x9a, 0x66, 0x4c, 0x08, 0xd0, 0x9a, 0xdd, 0x4f,
	0x6e, 0xae, 0xaf, 0xba, 0x35, 0xec, 0x40, 0x7b, 0xc6, 0xaf, 0xbf, 0x5f, 0x2e, 0xc2, 0xae, 0x73,
	0xfe, 0x09, 0x5e, 0xff, 0x37, 0x20, 0xa3, 0x5f, 0xf1, 0xf0, 0x72, 0x11, 0x4e, 0xbb, 0x35, 0x3c,
	0x01, 0x6f, 0x7e, 0x3f, 0x9f, 0x85, 0xdf, 0xa6, 0xe1, 0xb4, 0xeb, 0x18, 0x6d, 0x1a, 0xde, 0x84,
	0x46, 0x73, 0x97, 0x2d, 0x6b, 0xf7, 0xc3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0x6a, 0x1f,
	0x81, 0xce, 0x03, 0x00, 0x00,
}
