// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scheduler/request.proto

package scheduler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateSchedulerRequest struct {
	Description string                     `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Expression  string                     `protobuf:"bytes,2,opt,name=expression" json:"expression,omitempty"`
	Labels      []string                   `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty"`
	Type        SchedulerType              `protobuf:"varint,4,opt,name=type,enum=scheduler.SchedulerType" json:"type,omitempty"`
	Status      SchedulerStatus            `protobuf:"varint,5,opt,name=status,enum=scheduler.SchedulerStatus" json:"status,omitempty"`
	StartDate   *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=startDate" json:"startDate,omitempty"`
	EndDate     *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=endDate" json:"endDate,omitempty"`
	Properties  []*SchedulerProperty       `protobuf:"bytes,8,rep,name=properties" json:"properties,omitempty"`
	Meta        *SchedulerMeta             `protobuf:"bytes,9,opt,name=meta" json:"meta,omitempty"`
}

func (m *CreateSchedulerRequest) Reset()                    { *m = CreateSchedulerRequest{} }
func (m *CreateSchedulerRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSchedulerRequest) ProtoMessage()               {}
func (*CreateSchedulerRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *CreateSchedulerRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateSchedulerRequest) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

func (m *CreateSchedulerRequest) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *CreateSchedulerRequest) GetType() SchedulerType {
	if m != nil {
		return m.Type
	}
	return SchedulerType_PUBLIC
}

func (m *CreateSchedulerRequest) GetStatus() SchedulerStatus {
	if m != nil {
		return m.Status
	}
	return SchedulerStatus_CREATED
}

func (m *CreateSchedulerRequest) GetStartDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *CreateSchedulerRequest) GetEndDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *CreateSchedulerRequest) GetProperties() []*SchedulerProperty {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *CreateSchedulerRequest) GetMeta() *SchedulerMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type UpdateSchedulerRequest struct {
}

func (m *UpdateSchedulerRequest) Reset()                    { *m = UpdateSchedulerRequest{} }
func (m *UpdateSchedulerRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateSchedulerRequest) ProtoMessage()               {}
func (*UpdateSchedulerRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type DeleteSchedulerRequest struct {
}

func (m *DeleteSchedulerRequest) Reset()                    { *m = DeleteSchedulerRequest{} }
func (m *DeleteSchedulerRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteSchedulerRequest) ProtoMessage()               {}
func (*DeleteSchedulerRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type GetSchedulerRequest struct {
}

func (m *GetSchedulerRequest) Reset()                    { *m = GetSchedulerRequest{} }
func (m *GetSchedulerRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSchedulerRequest) ProtoMessage()               {}
func (*GetSchedulerRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func init() {
	proto.RegisterType((*CreateSchedulerRequest)(nil), "scheduler.CreateSchedulerRequest")
	proto.RegisterType((*UpdateSchedulerRequest)(nil), "scheduler.UpdateSchedulerRequest")
	proto.RegisterType((*DeleteSchedulerRequest)(nil), "scheduler.DeleteSchedulerRequest")
	proto.RegisterType((*GetSchedulerRequest)(nil), "scheduler.GetSchedulerRequest")
}

func init() { proto.RegisterFile("scheduler/request.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xa9, 0x9d, 0x9d, 0x7d, 0x03, 0x0f, 0x11, 0x6b, 0x28, 0xa2, 0x65, 0xa7, 0x1e, 0xa4,
	0x83, 0xea, 0xc1, 0x83, 0x37, 0x07, 0x9e, 0x04, 0xc9, 0xe6, 0x1f, 0x90, 0xad, 0xcf, 0x59, 0x68,
	0x97, 0x98, 0xbc, 0x82, 0xfb, 0xaf, 0xfc, 0x13, 0x65, 0xe9, 0xba, 0x0d, 0x29, 0x78, 0xcc, 0xf7,
	0xfd, 0x5e, 0xde, 0x97, 0x2f, 0x70, 0x65, 0x97, 0x9f, 0x58, 0x34, 0x15, 0x9a, 0x89, 0xc1, 0xaf,
	0x06, 0x2d, 0x65, 0xda, 0x28, 0x52, 0x2c, 0xdc, 0x1b, 0xf1, 0xed, 0x4a, 0xa9, 0x55, 0x85, 0x13,
	0x67, 0x2c, 0x9a, 0x8f, 0x09, 0x95, 0x35, 0x5a, 0x92, 0xb5, 0x6e, 0xd9, 0x38, 0x3a, 0x5c, 0xb2,
	0x54, 0x75, 0xad, 0xd6, 0xad, 0x3e, 0xfe, 0xf1, 0x21, 0x7a, 0x36, 0x28, 0x09, 0x67, 0x1d, 0x20,
	0xda, 0x25, 0x2c, 0x81, 0x51, 0x81, 0x76, 0x69, 0x4a, 0x4d, 0xa5, 0x5a, 0x73, 0x2f, 0xf1, 0xd2,
	0x50, 0x1c, 0x4b, 0xec, 0x06, 0x00, 0xbf, 0xb5, 0x41, 0x6b, 0xb7, 0xc0, 0x89, 0x03, 0x8e, 0x14,
	0x16, 0x41, 0x50, 0xc9, 0x05, 0x56, 0x96, 0xfb, 0x89, 0x9f, 0x86, 0x62, 0x77, 0x62, 0x77, 0x30,
	0xa0, 0x8d, 0x46, 0x3e, 0x48, 0xbc, 0xf4, 0x3c, 0xe7, 0xd9, 0x3e, 0x5b, 0xb6, 0x0f, 0x31, 0xdf,
	0x68, 0x14, 0x8e, 0x62, 0x39, 0x04, 0x96, 0x24, 0x35, 0x96, 0x9f, 0x3a, 0x3e, 0xee, 0xe3, 0x67,
	0x8e, 0x10, 0x3b, 0x92, 0x3d, 0x42, 0x68, 0x49, 0x1a, 0x9a, 0x4a, 0x42, 0x1e, 0x24, 0x5e, 0x3a,
	0xca, 0xe3, 0xac, 0xed, 0x28, 0xeb, 0x3a, 0xca, 0xe6, 0x5d, 0x47, 0xe2, 0x00, 0xb3, 0x07, 0x18,
	0xe2, 0xba, 0x70, 0x73, 0xc3, 0x7f, 0xe7, 0x3a, 0x94, 0x3d, 0x01, 0x68, 0xa3, 0x34, 0x1a, 0x2a,
	0xd1, 0xf2, 0xb3, 0xc4, 0x4f, 0x47, 0xf9, 0x75, 0x5f, 0xce, 0xb7, 0x96, 0xda, 0x88, 0x23, 0x7e,
	0xdb, 0x47, 0x8d, 0x24, 0x79, 0xe8, 0x16, 0xf6, 0xf6, 0xf1, 0x8a, 0x24, 0x85, 0xa3, 0xc6, 0x1c,
	0xa2, 0x77, 0x5d, 0xf4, 0xfc, 0xd8, 0xd6, 0x99, 0x62, 0x85, 0x3d, 0xce, 0x25, 0x5c, 0xbc, 0x20,
	0xfd, 0x95, 0x17, 0x81, 0x7b, 0xd3, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15, 0xae, 0x32,
	0xfd, 0x63, 0x02, 0x00, 0x00,
}
